name: Continuous Integration

on: 
  push:
   branches:
    - master
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: |
          pwd
          ls
          npm ci
          npm run pw
          npm run lint
          npm run test

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
